detect_duration: 10
camera_id: 0
enable_multithread_detect: true
retrack_queue_size: 10
fps: 60
send_posedata_udp: true
port: 4242
udp_host: 127.000.000.1
use_ft: false
use_npclient: false
cov_Q_lm: 0.089125093813374565
cov_Q_fsa: 0.095499258602143575
cov_T: 0.0010471285480508996
cov_V: 0.5745659676818673
cov_W: 28.336750230328732
ekf_predict_dt: 0.01
use_ekf: false
disp_duration: 30
disp_max_series_size: 10000
fsa_pnp_mixture_rate: 0.45000000000000001
hotkey_joystick_name0: Saitek Pro Flight X-55 Rhino Throttle
hotkey_joystick_button0: 1
hotkey_joystick_name1: ""
hotkey_joystick_button1: 0
landmark_detect_method: 3
pitch_offset_fsa_pnp: 0.191986218
cervical_face_model_x: 0.16
cervical_face_model_y: 0.16
cervical_face_model: -0.1
enable_gpu: false
enable_auto_expo: true
camera_expo: 0.90000000000000002
camera_gain: 0.5
enable_face_spd_est: true

inp_bound_x: 0.3
inp_bound_y: 0.1
inp_bound_z: 0.1
out_bound_x: 0.75
out_bound_y: 0.8
out_bound_z: 0.6
expo_trans_x: 0
expo_trans_y: 0
expo_trans_z: 0
inp_bound_roll: 180
inp_bound_pitch: 20
inp_bound_yaw: 25
out_bound_roll: 180
out_bound_pitch: 180
out_bound_yaw: 180
expo_eul_roll: 0.15
expo_eul_pitch: 0.15
expo_eul_yaw: 0.15
use_accela: true
accela_rot_smoothing: 0.05
accela_rot_deadzone: 1.0
accela_pos_smoothing: 0.03
accela_pos_deadzone: 0.03